#!/bin/bash 
#
# Wrapper script to run the debian package build of the zfsonlinux
# package
#

DEBUG_BUILD_OPTION=""
BUILD_VERSION_BEGIN=1000 

if [ $2"" == "debug" ]
then
	DEBUG_BUILD_OPTION="--enable-debug"
    BUILD_VERSION_BEGIN=1500
fi

BUILD_VERSION=`expr $BUILD_VERSION_BEGIN + $1`

pushd spl-0.6.4.2
sed -i "s/Release\:\s*.*/Release\:      $BUILD_VERSION/g" META
./autogen.sh
./configure $DEBUG_BUILD_OPTION
make deb-utils deb-kmod
for i in `ls *.deb`; do  dpkg -i $i; done

popd

pushd zfs-0.6.4.2
sed -i "s/Release\:\s*.*/Release\:      $BUILD_VERSION/g" META
./autogen.sh
./configure $DEBUG_BUILD_OPTION
make deb-utils deb-kmod
popd

rm -rf debs
mkdir debs

cp -f spl-0.6.4.2/*.deb debs/
cp zfs-0.6.4.2/*.deb debs/

chmod -R 777 *
exit $?
